export const CORALMULTI_LIST_REQUEST = 'CORALMULTI_LIST_REQUEST'
export const CORALMULTI_LIST_SUCCESS = 'CORALMULTI_LIST_SUCCESS'
export const CORALMULTI_LIST_FAIL = 'CORALMULTI_LIST_FAIL'
//store select contants

export const CORALMULTI_DETAILS_REQUEST = 'CORALMULTI_DETAILS_REQUEST'
export const CORALMULTI_DETAILS_SUCCESS = 'CORALMULTI_DETAILS_SUCCESS'
export const CORALMULTI_DETAILS_FAIL = 'CORALMULTI_DETAILS_FAIL'

export const CORALMULTI_DELETE_REQUEST = 'CORALMULTI_DELETE_REQUEST'
export const CORALMULTI_DELETE_SUCCESS = 'CORALMULTI_DELETE_SUCCESS'
export const CORALMULTI_DELETE_FAIL = 'CORALMULTI_DELETE_FAIL'

export const CORALMULTI_CREATE_REQUEST = 'CORALMULTI_CREATE_REQUEST'
export const CORALMULTI_CREATE_SUCCESS = 'CORALMULTI_CREATE_SUCCESS'
export const CORALMULTI_CREATE_FAIL = 'CORALMULTI_CREATE_FAIL'
export const CORALMULTI_CREATE_RESET = 'CORALMULTI_CREATE_RESET'

// export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
// export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
// export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
// export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

// export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
// export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
// export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
// export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

// export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
// export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
// export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'
