export const TEMPERATURE_LIST_REQUEST = 'TEMPERATURE_LIST_REQUEST'
export const TEMPERATURE_LIST_SUCCESS = 'TEMPERATURE_LIST_SUCCESS'
export const TEMPERATURE_LIST_FAIL = 'TEMPERATURE_LIST_FAIL'

export const TEMPERATURE_DELETE_REQUEST = 'TEMPERATURE_DELETE_REQUEST'
export const TEMPERATURE_DELETE_SUCCESS = 'TEMPERATURE_DELETE_SUCCESS'
export const TEMPERATURE_DELETE_FAIL = 'TEMPERATURE_DELETE_FAIL'

export const TEMPERATURE_CREATE_REQUEST = 'TEMPERATURE_CREATE_REQUEST'
export const TEMPERATURE_CREATE_SUCCESS = 'TEMPERATURE_CREATE_SUCCESS'
export const TEMPERATURE_CREATE_FAIL = 'TEMPERATURE_CREATE_FAIL'
export const TEMPERATURE_CREATE_RESET = 'TEMPERATURE_CREATE_RESET'

